### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by saintdrug** [trustedsec/social-engineer-toolkit#159]
Hey guys just as i managed to have everything work, i did a multi attack after done:

i try to run setoolkit and get this:

*] Checking to see if bleeding-edge repos are active.
[*] Bleeding edge already active..Moving on..
Traceback (most recent call last):
  File "./setoolkit", line 94, in <module>
    update_config()
  File "/root/social-engineer-toolkit/src/core/update_config.py", line 117, in update_config
    value = line[1]
IndexError: list index out of range
root@no-limit-clan:~/social-engineer-toolkit# git pull
Already up-to-date.
root@no-limit-clan:~/social-engineer-toolkit# 

and i rm -rf social-engineer-toolkit

then git clone again same problem.

**Comment by saintdrug** [comment]
hmm i am missing also the set directory, is there a way to uninstall and reinstall everything? if so can you please advise.

oot@no-limit-clan:~/Desktop/Dropbox/Kali/social-engineer-toolkit# setoolkit
/usr/bin/setoolkit: line 3: cd: /usr/share/set/: No such file or directory
[*] Checking to see if bleeding-edge repos are active.
[*] Bleeding edge already active..Moving on..
Traceback (most recent call last):
  File "setoolkit", line 94, in <module>
    update_config()
  File "/usr/share/setoolkit/src/core/update_config.py", line 117, in update_config
    value = line[1]
IndexError: list index out of range

**Comment by saintdrug** [comment]
Yeah seems whatever I do I cannot make it work, on my other notebook its working fine.

seems I cannot / whatever I do to remove it and reinstall its always giving me the same error

**Comment by saintdrug** [comment]
after 4 days I managed to fix it.
if someone crashes the toolkit let me know thanks all.
