### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by darqitecht** [trustedsec/social-engineer-toolkit#242]
OS X El capitan...

`python3 seupdate `

or

`python3 setoolkit`

```
Traceback (most recent call last):
  File "seupdate", line 21, in <module>
    from src.core.setcore import *
  File "/Users/*****/****/set/src/core/setcore.py", line 1783
    return result
                ^

TabError: inconsistent use of tabs and spaces in indentation
```

So, the way to fix quite simple, go to that line and replace the "TAB" by white spaces and solved!

**Comment by trustedsec** [comment]
Feel free to submit a pull request
