### ISSUE TITLE
Full Screen Attack Method

### ISSUE THREAD

**Issue by Thestorm77** [trustedsec/social-engineer-toolkit#245]
When selecting 
1. Social Engineering attack 
2. Website Attack Vectors
3. Full Screen Attack Method 

receive the following error : " Traceback (most recent call last):
  File "./setoolkit", line 239, in <module>
    import src.core.set
  File "/root/tools/social-engineer-toolkit/src/core/set.py", line 158, in <module>
    import full
  File "/root/tools/social-engineer-toolkit/src/webattack/fsattack/full.py", line 7, in <module>
    from .fsattacks import *
ValueError: Attempted relative import in non-package"

**Comment by trustedsec** [comment]
Awesome, thanks for the bug report! I've gone ahead and fixed this one in version 7.3 which I anticipate to be released within a week.
