### ISSUE TITLE
ERROR!!   Process Process-1:

### ISSUE THREAD

**Issue by kali64amd** [trustedsec/social-engineer-toolkit#481]
Hi, there 

I'm getting this error (see below) while opening SET so please advise..

Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/set/src/core/setcore.py", line 881, in pull_version
    version = urlopen(url).read().rstrip().decode('utf-8')
  File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 450, in open_https
    'got a bad status line', None)
IOError: ('http protocol error', 0, 'got a bad status line', None)
 Select from the menu:

**Comment by trustedsec** [comment]
Looks like your Python install is borked or you don't have Internet access to pull updates..

**Comment by kaoscoach** [comment]
I get the same error. How do you configure SET to utilize proxies?
