### ISSUE TITLE
SSL with setoolkit not work with 7.7.9

### ISSUE THREAD

**Issue by hohenh** [trustedsec/social-engineer-toolkit#567]
Hi,

_I use debian, kali, i have the newest version 7.7.9, but lot of error with SSL for the https clone_

**Actualy the SSL option in /etc/setoolkit/set.conf, didn't work.**
WEBATTACK_SSL=ON
SELF_SIGNED_CERT=ON

**After option : 1 - 2 - 3 - 2 this make this error -->**
```

> The best way to use this attack is if username and password form
> fields are available. Regardless, this captures all POSTs on a website.
> Generating a 1024 bit RSA private key
> .........................++++++
> .....................++++++
> writing new private key to 'private/cakey.pem'
> Enter PEM pass phrase:
> Verifying - Enter PEM pass phrase:
> -----
> You are about to be asked to enter information that will be incorporated
> into your certificate request.
> What you are about to enter is what is called a Distinguished Name or a DN.
> There are quite a few fields but you can leave some blank
> For some fields there will be a default value,
> If you enter '.', the field will be left blank.
> -----
> Organization Name (company) [The Sample Company]:
> Organizational Unit Name (department, division) []:
> Email Address []:                      
> Locality Name (city, district) [Metropolis]:
> State or Province Name (full name) [New York]:
> Country Name (2 letter code) [US]:
> Common Name (hostname, IP, or your name) []:
> [*] You may need to copy /var/www/* into /var/www/html depending on where your directory structure is.
> Press {return} if you understand what we're saying here.
> [*] The Social-Engineer Toolkit Credential Harvester Attack
> [*] Credential Harvester is running on port 443
> [*] Information will be displayed to you as it arrives below:
> [*] Starting built-in SSL server
> Enter PEM pass phrase:
>
> ----------------------------------------
> Exception happened during processing of request from [108.78.2.14, 44446]
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
>     self.process_request(request, client_address)
>   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
>     self.finish_request(request, client_address)
>   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
>     self.handle()
>   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
>     self.handle_one_request()
>   File "/usr/lib/python2.7/BaseHTTPServer.py", line 310, in handle_one_request
>     self.raw_requestline = self.rfile.readline(65537)
>   File "/usr/lib/python2.7/socket.py", line 480, in readline
>     data = self._sock.recv(self._rbufsize)
>   File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 1684, in recv
>     self._raise_ssl_error(self._ssl, result)
>   File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 1546, in _raise_ssl_error
>     _raise_current_error()
>   File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
>     raise exception_type(errors)
> Error: [('SSL routines', 'ssl3_get_record', 'http request')]
> ----------------------------------------
> [!] Something went wrong.. Printing error: [('SSL routines', 'SSL_shutdown', 'shutdown while in init')]
```

**After if i leave with 99 i have this error -->**

`[!] Something went wrong, ptinting the error: [Errno 2] No such file or directory: 'src/core/set.version'`

**And if i try to run setoolkit after this error i can't i have this error -->**

```
Traceback (most recent call last):
  File "setoolkit", line 50, in <module>
    import src.core.setcore as core
  File "/usr/share/setoolkit/src/core/setcore.py", line 8, in <module>
    import socket
  File "/usr/share/setoolkit/socket.py", line 68, in <module>
    from _ssl import \
ImportError: cannot import name RAND_egd
```

**Finaly i do reinstall setoolkit, so is it possible to make that work, because is a very big bug and crash.**

_Thank for help_

**Comment by tama10111** [comment]
I don't know if you cloned the repo, but to gain some time, you can just remove socket.py and socket.pyc from the root

**Comment by hohenh** [comment]
Ok tama10111, for the moment i create apache server ssl, and i dont use the option SSL in setoolkit, and that work. But i do try remove socket.py and socket.pyc root, for test. Thank

**Comment by christophermillard24** [comment]
hey hohehn i dont know if you still use this website but i am having the same problem you had with your setoolkit :~# setoolkit
Traceback (most recent call last):
  File "./setoolkit", line 50, in <module>
    import src.core.setcore as core
  File "/usr/share/set/src/core/setcore.py", line 8, in <module>
    import socket
  File "/usr/share/set/socket.py", line 68, in <module>
    from _ssl import \
ImportError: cannot import name RAND_egd
please id really appreciate your help
