### ISSUE TITLE
SET Crashes and will not restart - Running TLS website - ImportError: cannot import name RAND_egd

### ISSUE THREAD

**Issue by aposlte** [trustedsec/social-engineer-toolkit#606]
Encountering this issue is a fully upgraded kali rolling image.  Have also reproduced it in 2018.3.

Configuration
Using Let's Encrypt generated certs for the domain.

Have /etc/setoolkit/set.config configured as...
WEBATTACK_SSL=ON
PEM_CLIENT=/etc/letsencrypt/live/test.domain.com/cert.pem
PEM_SERVER=/etc/letsencrypt/live/test.domain.com/privkey.pem

Running
Social-Engineering Attacks ->Website Attack Vectors -> Credential Harvester Attack Method -> Site Cloner & Website Templates.

Issue
While the website is running to allow connections and harvest credentials SET crashes with the following error.
----------------------------------------
Exception happened during processing of request from ('client.ip.addr.here', 52300)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 293, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 310, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 1791, in recv
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 1639, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
SysCallError: (104, 'ECONNRESET')
----------------------------------------
[!] Something went wrong.. Printing error: (32, 'EPIPE')

And then when attempting to restart SET, it will no longer start up.
root@kali:~# setoolkit
Traceback (most recent call last):
  File "setoolkit", line 50, in <module>
    import src.core.setcore as core
  File "/usr/share/setoolkit/src/core/setcore.py", line 8, in <module>
    import socket
  File "/usr/share/setoolkit/socket.py", line 68, in <module>
    from _ssl import \
ImportError: cannot import name RAND_egd

**Comment by trustedsec** [comment]
Fixed in latest version 8.0.2
