### ISSUE TITLE
How to specify python path

### ISSUE THREAD

**Issue by 937325203** [trustedsec/social-engineer-toolkit#617]
### But in my MacOS System environment,command `python` means python2.7 , command `python3` means python3. Will when i execute setoolkit,i see this:

```
[!] The python-pycrypto python module not installed. You will lose the ability for encrypted communications.
[!] Metasploit path not found. These payloads will be disabled.
[!] Please configure Metasploit's path in the /etc/setoolkit/set.config file.
[!] The python-pycrypto python module not installed. You will lose the ability to use multi-pyinjector.
[-] New set.config.py file generated on: 2019-04-08 08:15:24.515278
[-] Verifying configuration update...
[*] Update verified, config timestamp is: 2019-04-08 08:15:24.515278
[*] SET is using the new config, no need to restart

            :::===  :::===== :::====
            :::     :::      :::====
             =====  ======     ===
                === ===        ===
            ======  ========   ===


[---]        The Social-Engineer Toolkit (SET)         [---]
[---]        Created by: David Kennedy (ReL1K)         [---]
                      Version: 8.0
                  Codename: 'Maverick - BETA'
[---]        Follow us on Twitter: @TrustedSec         [---]
[---]        Follow me on Twitter: @HackingDave        [---]
[---]       Homepage: https://www.trustedsec.com       [---]
        Welcome to the Social-Engineer Toolkit (SET).
         The one stop shop for all of your SE needs.

   The Social-Engineer Toolkit is a product of TrustedSec.

           Visit: https://www.trustedsec.com

   It's easy to update using the PenTesters Framework! (PTF)
Visit https://github.com/trustedsec/ptf to update all your tools!


Process Process-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/BigBai/set/src/core/setcore.py", line 879, in pull_version
    version = urlopen(url).read().rstrip().decode('utf-8')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1274, in connect
    server_hostname=server_hostname)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 352, in wrap_socket
    _context=self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 579, in __init__
    self.do_handshake()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [Errno 32] Broken pipe
 Select from the menu:

   1) Social-Engineering Attacks
   2) Penetration Testing (Fast-Track)
   3) Third Party Modules
   4) Update the Social-Engineer Toolkit
   5) Update SET configuration
   6) Help, Credits, and About

  99) Exit the Social-Engineer Toolkit
```

**Comment by 937325203** [comment]
???

**Comment by trustedsec** [comment]
Easiest way is to use MacPorts.

sudo port install python_select
port search python # Search for version you are looking for
sudo port install python27
sudo port select --set python python27

**Comment by A-23187** [comment]
There is a trick to solve this issue. You can see more [here](http://redsymbol.net/articles/env-and-python-scripts-version/) :)

And in my case, I create a soft link `/usr/share/set/python` whose target is `/usr/bin/python3.7`, the path of my python3 , and then create a file `setoolkit` whose content is
```
#!/bin/bash
SET_PATH="/usr/share/set"
export PATH="$SET_PATH:$PATH"
cd $SET_PATH && ./setoolkit "$@"
```
And then 
```
chmod +x setoolkit
mv setoolkit /usr/bin # you can move it to any directory in PATH variable you want
```
