### ISSUE TITLE
link error

### ISSUE THREAD

**Issue by ptsxcash** [trustedsec/social-engineer-toolkit#674]
Exception happened during processing of request from ('172.20.10.3', 54880)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 394, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
AttributeError: 'SETHandler' object has no attribute 'rfile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 722, in __init__
    self.finish()
  File "/usr/lib/python3.7/socketserver.py", line 777, in finish
    if not self.wfile.closed:
AttributeError: 'SETHandler' object has no attribute 'wfile'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('172.20.10.3', 54882)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 394, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
AttributeError: 'SETHandler' object has no attribute 'rfile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 722, in __init__
    self.finish()
  File "/usr/lib/python3.7/socketserver.py", line 777, in finish
    if not self.wfile.closed:
AttributeError: 'SETHandler' object has no attribute 'wfile'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('172.20.10.3', 54884)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 394, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
AttributeError: 'SETHandler' object has no attribute 'rfile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 722, in __init__
    self.finish()
  File "/usr/lib/python3.7/socketserver.py", line 777, in finish
    if not self.wfile.closed:
AttributeError: 'SETHandler' object has no attribute 'wfile'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('172.20.10.3', 54886)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 394, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
AttributeError: 'SETHandler' object has no attribute 'rfile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 722, in __init__
    self.finish()
  File "/usr/lib/python3.7/socketserver.py", line 777, in finish
    if not self.wfile.closed:
AttributeError: 'SETHandler' object has no attribute 'wfile'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('172.20.10.3', 54888)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 394, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
AttributeError: 'SETHandler' object has no attribute 'rfile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 722, in __init__
    self.finish()
  File "/usr/lib/python3.7/socketserver.py", line 777, in finish
    if not self.wfile.closed:
AttributeError: 'SETHandler' object has no attribute 'wfile'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('172.20.10.3', 54890)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 394, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
AttributeError: 'SETHandler' object has no attribute 'rfile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 722, in __init__
    self.finish()
  File "/usr/lib/python3.7/socketserver.py", line 777, in finish
    if not self.wfile.closed:
AttributeError: 'SETHandler' object has no attribute 'wfile'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('172.20.10.3', 54892)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 394, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
AttributeError: 'SETHandler' object has no attribute 'rfile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 722, in __init__
    self.finish()
  File "/usr/lib/python3.7/socketserver.py", line 777, in finish
    if not self.wfile.closed:
AttributeError: 'SETHandler' object has no attribute 'wfile'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('172.20.10.3', 54894)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 394, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
AttributeError: 'SETHandler' object has no attribute 'rfile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 722, in __init__
    self.finish()
  File "/usr/lib/python3.7/socketserver.py", line 777, in finish
    if not self.wfile.closed:
AttributeError: 'SETHandler' object has no attribute 'wfile'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('172.20.10.3', 54896)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 394, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
AttributeError: 'SETHandler' object has no attribute 'rfile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 722, in __init__
    self.finish()
  File "/usr/lib/python3.7/socketserver.py", line 777, in finish
    if not self.wfile.closed:
AttributeError: 'SETHandler' object has no attribute 'wfile'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('172.20.10.3', 54898)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 394, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
AttributeError: 'SETHandler' object has no attribute 'rfile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 722, in __init__
    self.finish()
  File "/usr/lib/python3.7/socketserver.py", line 777, in finish
    if not self.wfile.closed:
AttributeError: 'SETHandler' object has no attribute 'wfile'
----------------------------------------
e "/usr/lib/python3.7/http/server.py", line 426, in handle

**Comment by masoodkamyab** [comment]
I have the same issue !
Is there any progress ?

**Comment by ptsxcash** [comment]
Download set tool manual

**Comment by CousinOkri** [comment]
I'm facing the same issue. Were you able to solve it ?

**Comment by ptsxcash** [comment]
> I'm facing the same issue. Were you able to solve it ?

download manually and its working

**Comment by CousinOkri** [comment]
> > I'm facing the same issue. Were you able to solve it ?
> 
> download manually and its working

That worked for me too. Thank you!!!

**Comment by trustedsec** [comment]
Just confirming, downloading this directly from GIT works but installed does not?

**Comment by CousinOkri** [comment]
> Just confirming, downloading this directly from GIT works but installed does not?

Yes, that's exactly what's happening. I was using the latest build of ParrotOS, if that's relevant.

**Comment by CousinOkri** [comment]
The new update broke it. It doesn't work even after installing directly from git now.

**Comment by trustedsec** [comment]
Its definitely a python2 to python3 conversion issue, if you run python2 setoolkit this works fine. I'll get a fix in soon.

**Comment by trustedsec** [comment]
Mostly done with the fix just need to do some code cleanup and testing. It’s due to a bug in python3 but luckily a fairly easy workaround. Should have it completed later tonight

**Comment by trustedsec** [comment]
Alright! This issue is fixed. Took a bit of a rewrite but seems very stable now. If you have any other issues let me know. Pushed in 8.0.3.
