### ISSUE TITLE
harvester issues with python3.8

### ISSUE THREAD

**Issue by swoth-f** [trustedsec/social-engineer-toolkit#720]
**Expected Behaviour**

Capture credentials when user navigates to spoofed site.

**Actual Behaviour**

Captures the email address and throws a bunch of exceptions.
Output:
[*] WE GOT A HIT! Printing the output:
POSSIBLE USERNAME FIELD FOUND: session[username_or_email]=j@email.com                                                                       
----------------------------------------                                                                                                    
Exception happened during processing of request from ('<sanitized-ipaddress>', 43662)                                                                
Traceback (most recent call last):                                                                                                          
  File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread                                                            
    self.finish_request(request, client_address)                                                                                            
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request                                                                    
    self.RequestHandlerClass(request, client_address, self)                                                                                 
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__                                                                          
    self.handle()                                                                                                                           
  File "/usr/lib/python3.8/http/server.py", line 427, in handle                                                                             
    self.handle_one_request()                                                                                                               
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request                                                                 
    method()                                                                                                                                
  File "/usr/share/set/src/webattack/harvester/harvester.py", line 334, in do_POST                                                          
    filewrite.write(cgi.escape("PARAM: " + line + "\n"))                                                                                    
AttributeError: module 'cgi' has no attribute 'escape'                                                                                      
----------------------------------------                                       
The only thing I was able to find when researching the above exceptions is that cgi.escape was removed in python3.8.  I don't know if this helps but I thought I would share what I found.

**Set Version** = 8.0.3

**Set in Kali**

Ran ``apt update && apt full-upgrade`` 

``lsb_release -rdc`` output:

Description:    Kali GNU/Linux Rolling
Release:        2020.2
Codename:       kali-rolling

**Comment by momobit** [comment]
Im exatly in your same situation!

**Comment by neorampage** [comment]
you need to add "import html" under "import cgi" and then change "cgi.escape" to "html.escape"

**Comment by swoth-f** [comment]
Will do. Thx

Sent from my iPhone

On Apr 21, 2020, at 9:51 PM, neorampage <notifications@github.com> wrote:

﻿

CAUTION:This email originated outside of Maryville University. Review links and attachments carefully before opening.


you need to add "import html" under "import cgi" and then change "cgi.escape" to "html.escape"

**Comment by giovanni0013** [comment]
> you need to add "import html" under "import cgi" and then change "cgi.escape" to "html.escap
hi where should I add them ??

**Comment by neorampage** [comment]
> > you need to add "import html" under "import cgi" and then change "cgi.escape" to "html.escap
> > hi where should I add them ??

edit this file "/usr/share/set/src/webattack/harvester/harvester.py" and add "import html" under "import cgi" and then change "cgi.escape" to "html.escape

**Comment by giovanni0013** [comment]
> > > you need to add "import html" under "import cgi" and then change "cgi.escape" to "html.escap
> 
> > > hi where should I add them ??
> 
> 
> 
> edit this file "/usr/share/set/src/webattack/harvester/harvester.py" and add "import html" under "import cgi" and then change "cgi.escape" to "html.escape
> 
> 


I added import html instead of import cgi and replaced cgi.escape with html.escape

but the problem remains
Filewrite.write(cgi.escape(param: “ +Line + “\n”))
AttributeError: module ‘cgi’ has no attribute ‘escape’

**Comment by neorampage** [comment]
> > > > you need to add "import html" under "import cgi" and then change "cgi.escape" to "html.escap
> > 
> > 
> > > > hi where should I add them ??
> > 
> > 
> > edit this file "/usr/share/set/src/webattack/harvester/harvester.py" and add "import html" under "import cgi" and then change "cgi.escape" to "html.escape
> 
> I added import html instead of import cgi and replaced cgi.escape with html.escape
> 
> but the problem remains
> Filewrite.write(cgi.escape(param: “ +Line + “\n”))
> AttributeError: module ‘cgi’ has no attribute ‘escape’

in your file, you need to have something like this
"import cgi
import html" 
and 
Filewrite.write(html.escape(param: “ +Line + “\n”))

**Comment by giovanni0013** [comment]
yes I have them, but on set it keeps giving me the same error![Uploading 80046155...]()![Uploading 80046163...]()

**Comment by giovanni0013** [comment]
tell me where I can contact you so I put the photos

**Comment by neorampage** [comment]
you can chat me in telegram, i have the same nickname

**Comment by neorampage** [comment]
> tell me where I can contact you so I put the photos

you can chat me in telegram, i have the same nickname

**Comment by neorampage** [comment]
[harvester.py.zip](https://github.com/trustedsec/social-engineer-toolkit/files/4519813/harvester.py.zip)

For people who do not work making this change, here I leave my file, just replace it with the correct path.

**Comment by devilmen80** [comment]
Hello when I must replace this file .zip mate?? I have same problem of these guys. Thanks

**Comment by devilmen80** [comment]
> [harvester.py.zip](https://github.com/trustedsec/social-engineer-toolkit/files/4519813/harvester.py.zip)
> 
> For people who do not work making this change, here I leave my file, just replace it with the correct path.

Hello mate I have same problem of these guys...where i must replace this zip file? Thanks.

**Comment by neorampage** [comment]
> > [harvester.py.zip](https://github.com/trustedsec/social-engineer-toolkit/files/4519813/harvester.py.zip)
> > For people who do not work making this change, here I leave my file, just replace it with the correct path.
> 
> Hello mate I have same problem of these guys...where i must replace this zip file? Thanks.

see yo error and yo have an error in harvester.py, in that file path you are going to replace the file

**Comment by devilmen80** [comment]
> > > [harvester.py.zip](https://github.com/trustedsec/social-engineer-toolkit/files/4519813/harvester.py.zip)
> > > For people who do not work making this change, here I leave my file, just replace it with the correct path.
> > 
> > 
> > Hello mate I have same problem of these guys...where i must replace this zip file? Thanks.
> 
> see yo error and yo have an error in harvester.py, in that file path you are going to replace the file

Thanks for your help..I'm new...download this file in harrvester.py and exstract it in same folder and delete old file?? It's right?

**Comment by neorampage** [comment]
> > > > [harvester.py.zip](https://github.com/trustedsec/social-engineer-toolkit/files/4519813/harvester.py.zip)
> > > > For people who do not work making this change, here I leave my file, just replace it with the correct path.
> > > 
> > > 
> > > Hello mate I have same problem of these guys...where i must replace this zip file? Thanks.
> > 
> > 
> > see yo error and yo have an error in harvester.py, in that file path you are going to replace the file
> 
> Thanks for your help..I'm new...download this file in harrvester.py and exstract it in same folder and delete old file?? It's right?

yes

**Comment by devilmen80** [comment]
Thanks a lot mate... I will try just possible and i''ll let you know. Cheers:)

> > > > > [harvester.py.zip](https://github.com/trustedsec/social-engineer-toolkit/files/4519813/harvester.py.zip)
> > > > > For people who do not work making this change, here I leave my file, just replace it with the correct path.
> > > > 
> > > > 
> > > > Hello mate I have same problem of these guys...where i must replace this zip file? Thanks.
> > > 
> > > 
> > > see yo error and yo have an error in harvester.py, in that file path you are going to replace the file
> > 
> > 
> > Thanks for your help..I'm new...download this file in harrvester.py and exstract it in same folder and delete old file?? It's right?
> 
> yes

Thanks a lot mate... I will try just possible and i''ll let you know. Cheers:)

**Comment by devilmen80** [comment]
> > > > > [harvester.py.zip](https://github.com/trustedsec/social-engineer-toolkit/files/4519813/harvester.py.zip)
> > > > > For people who do not work making this change, here I leave my file, just replace it with the correct path.
> > > > 
> > > > 
> > > > Hello mate I have same problem of these guys...where i must replace this zip file? Thanks.
> > > 
> > > 
> > > see yo error and yo have an error in harvester.py, in that file path you are going to replace the file
> > 
> > 
> > Thanks for your help..I'm new...download this file in harrvester.py and exstract it in same folder and delete old file?? It's right?
> 
> yes

I don't understand. But the victim must be connected in our same net??bcuz if If I open link out form net form which making attack link don't working...thanks

**Comment by neorampage** [comment]
exactly, you need something to use out od the net, for example ngrok

**Comment by devilmen80** [comment]
> exactly, you need something to use out od the net, for example 

> exactly, you need something to use out od the net, for example ngrok

Thanks mate anyway your zip file working good. I don't understand where save the file with password...ialso I have another question. With black eye I don't have any link...is bcuz I don't have ngrok? Thanks

**Comment by neorampage** [comment]
you need to see very carefully setoolkit there can you see the file path where the credentials are save, i dont know about black eye

**Comment by kushagra055** [comment]
> you need to see very carefully setoolkit there can you see the file path where the credentials are save, i dont know about black eye

i have a new problem after replacing harvester.py.zip
![Screenshot_2020-05-04_01-45-59](https://user-images.githubusercontent.com/64585151/80924910-9ced2c80-8da9-11ea-8fd9-b5725f3c3ca1.png)
it is not showing password

**Comment by iTruth** [comment]
> 
> 
> > you need to see very carefully setoolkit there can you see the file path where the credentials are save, i dont know about black eye
> 
> i have a new problem after replacing harvester.py.zip
> ![Screenshot_2020-05-04_01-45-59](https://user-images.githubusercontent.com/64585151/80924910-9ced2c80-8da9-11ea-8fd9-b5725f3c3ca1.png)
> it is not showing password

It's probably your website problem..


> 
> 
> you need to add "import html" under "import cgi" and then change "cgi.escape" to "html.escape"

It's worked for me when I use google template website

**Comment by Darkentay** [comment]
![anotationerror](https://user-images.githubusercontent.com/43728964/82280466-4fee8600-9965-11ea-82b7-ade9778deb88.jpg)

keeps giving error, and now... help me
UnboundLocalError:  local avaliable 'html' referenced before assignment

**Comment by neorampage** [comment]
> ![anotationerror](https://user-images.githubusercontent.com/43728964/82280466-4fee8600-9965-11ea-82b7-ade9778deb88.jpg)
> 
> keeps giving error, and now... help me
> UnboundLocalError: local avaliable 'html' referenced before assignment

search that variable, i think is in line 416

**Comment by TheRicky90** [comment]
> > you need to see very carefully setoolkit there can you see the file path where the credentials are save, i dont know about black eye
> 
> i have a new problem after replacing harvester.py.zip
> ![Screenshot_2020-05-04_01-45-59](https://user-images.githubusercontent.com/64585151/80924910-9ced2c80-8da9-11ea-8fd9-b5725f3c3ca1.png)
> it is not showing password


use this haevester.py ist the most powerfull at this time..

https://github.com/trustedsec/social-engineer-toolkit/blob/master/src/webattack/harvester/harvester.py

**Comment by devilmen80** [comment]
> > > you need to see very carefully setoolkit there can you see the file path where the credentials are save, i dont know about black eye
> > 
> > 
> > i have a new problem after replacing harvester.py.zip
> > ![Screenshot_2020-05-04_01-45-59](https://user-images.githubusercontent.com/64585151/80924910-9ced2c80-8da9-11ea-8fd9-b5725f3c3ca1.png)
> > it is not showing password
> 
> use this haevester.py ist the most powerfull at this time..
> 
> https://github.com/trustedsec/social-engineer-toolkit/blob/master/src/webattack/harvester/harvester.py

Hello mate.
Make download of last version of setoolkit on githube then replace all old files with new. After replace again your file harvester...it works fine with me. Regards

**Comment by sarah199999** [comment]
hi I have the same issue, how i can replace the files

**Comment by Amine07a** [comment]
I think the issue is the same even after setting html.escape and the html first ,, the cloning is so bad

**Comment by HackingDave** [comment]
Addressed in SET 8.1.1 as part of the packaging, dependency, and Python runtime modernization. Please pull latest master and open a new issue with current reproduction steps if the problem still occurs.
