### ISSUE TITLE
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

### ISSUE THREAD

**Issue by lmh122** [trustedsec/social-engineer-toolkit#723]
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1319, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1392, in connect
    super().connect()
  File "/usr/lib/python3.8/http/client.py", line 915, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/set/src/core/setcore.py", line 879, in pull_version
    version = urlopen(url).read().rstrip().decode('utf-8')
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1362, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1322, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
Description:    Kali GNU/Linux Rolling
Release:        2020.2
Codename:       kali-rolling

**Comment by Bowser1704** [comment]
same issue.

**Comment by lmh122** [comment]
This doesn't seem to affect usage

**Comment by lenny-lyn** [comment]
How to slove this question

**Comment by 15870587094** [comment]
我也是这样，有没有解决方案啊

**Comment by ak47ak50** [comment]
If you can ping raw.githubusercontent.com well, this problem will be solved. So open Virtual Network Editor in VMware and modify  DNS in NAT mode, the DNS is 8.8.8.8, all is ok.

**Comment by HackingDave** [comment]
Addressed in SET 8.1.1 as part of the packaging, dependency, and Python runtime modernization. Please pull latest master and open a new issue with current reproduction steps if the problem still occurs.
