### ISSUE TITLE
site clone an harvester 

### ISSUE THREAD

**Issue by kasem545** [trustedsec/social-engineer-toolkit#730]
Exception happened during processing of request from ('192.168.14.178', 56194)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/share/setoolkit/src/webattack/harvester/harvester.py", line 415, in do_POST
    filewrite.write(cgi.escape("PARAM: " + line + "\n"))
AttributeError: module 'cgi' has no attribute 'escape'

**Set version 8.0.3 problem this  in ubuntu v20.04 & kali linux 2020**

**Comment by devilmen80** [comment]
I have some problem..I cannot resolve. I put html.escape instead of cdi but nothing..don't work.

**Comment by joneldominic** [comment]
Try this using this file. It works for me. [harvester.py.zip](https://github.com/trustedsec/social-engineer-toolkit/files/4639429/harvester.py.zip)



From https://github.com/trustedsec/social-engineer-toolkit/issues/720#issuecomment-618132243

**Comment by HackingDave** [comment]
Addressed in SET 8.1.1 as part of the packaging, dependency, and Python runtime modernization. Please pull latest master and open a new issue with current reproduction steps if the problem still occurs.
