### ISSUE TITLE
Something went wrong, printing the error: a bytes-like object is required, not 'str' when setting filename

### ISSUE THREAD

**Issue by lumontealegre** [trustedsec/social-engineer-toolkit#732]
**Expected Behaviour**

When creating infected media payload output expected.

**Actual Behaviour**

At end of interactive configuration set sends error:
Something went wrong, printing the error: a bytes-like object is required, not 'str'

**Set Version**

8.0.3

**Comment by hongson97** [comment]
try it!
https://github.com/trustedsec/social-engineer-toolkit/pull/749

**Comment by lmh122** [comment]
The error still exists

**Comment by lmh122** [comment]
After obtaining the password

192.168.0.115 - - [22/May/2020 07:39:01] "POST /ServiceLoginAuth HTTP/1.1" 302 -
----------------------------------------
Exception happened during processing of request from ('192.168.0.115', 55163)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/share/setoolkit/src/webattack/harvester/harvester.py", line 459, in do_POST
    self.wfile.write(html)
  File "/usr/lib/python3.8/socket.py", line 687, in write
    return self._sock.send(b)
TypeError: a bytes-like object is required, not 'module'

**Comment by HackingDave** [comment]
Addressed in SET 8.1.1 as part of the Python 3 web attack, credential harvester, static file, SSL, and legacy payload handling fixes. Please pull latest master and open a new issue with current reproduction steps if the problem still occurs.
