### ISSUE TITLE
My setoolkit doesnt sent me the username and password in terminal.

### ISSUE THREAD

**Issue by Sk-Kamal-Hossain** [trustedsec/social-engineer-toolkit#754]
When I try to get username and password using setoolkit phissing method nut its not work always show this is message
"[*] WE GOT A HIT! Printing the output:
----------------------------------------                                                                                 
Exception happened during processing of request from ('192.168.2.8', 46000)                                              
Traceback (most recent call last):                                                                                       
  File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread                                         
    self.finish_request(request, client_address)                                                                         
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request                                                 
    self.RequestHandlerClass(request, client_address, self)                                                              
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__                                                       
    self.handle()                                                                                                        
  File "/usr/lib/python3.8/http/server.py", line 427, in handle                                                          
    self.handle_one_request()                                                                                            
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request                                              
    method()                                                                                                             
  File "/usr/share/setoolkit/src/webattack/harvester/harvester.py", line 415, in do_POST                                 
    filewrite.write(cgi.escape("PARAM: " + line + "\n"))                                                                 
AttributeError: module 'cgi' has no attribute 'escape'     "
Help me to find out this problem solution.
Thank You.

**Comment by jamt0** [comment]
same error

**Comment by HackingDave** [comment]
Closing as an unauthorized account/password or account-access request. SET is for authorized security testing only and this repository will not provide help for unauthorized access.
