### ISSUE TITLE
Error while installing requirement.txt

### ISSUE THREAD

**Issue by Sourabh3131** [trustedsec/social-engineer-toolkit#764]
ERROR: Command errored out with exit status 1:
     command: /data/data/com.termux/files/usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-f6dzfdq1/pymssql/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-f6dzfdq1/pymssql/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /data/data/com.termux/files/usr/tmp/pip-pip-egg-info-v1im_rxv
         cwd: /data/data/com.termux/files/usr/tmp/pip-install-f6dzfdq1/pymssql/
    Complete output (7 lines):
    /data/data/com.termux/files/usr/lib/python3.8/site-packages/setuptools/dist.py:45: DistDeprecationWarning: Do not call this function
      warnings.warn("Do not call this function", DistDeprecationWarning)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/data/com.termux/files/usr/tmp/pip-install-f6dzfdq1/pymssql/setup.py", line 88, in <module>
        from Cython.Distutils import build_ext as _build_ext
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
![Uploading Screenshot_2020-06-19-10-24-51-083_com.termux.jpg…]

**Comment by MittKevv** [comment]
try `pip3 install cython` and then use the `pip3 install -r requirements.txt`

it helped in my case

**Comment by Sourabh3131** [comment]
I tried with this commands but it shows same error.
This time i cleared all user data of termux app and then reinstalled basic pakages. But same error is occured.

**Comment by erennnars** [comment]
Same error :/

**Comment by HackingDave** [comment]
Addressed in SET 8.1.1 as part of the packaging, dependency, and Python runtime modernization. Please pull latest master and open a new issue with current reproduction steps if the problem still occurs.
