### ISSUE TITLE
wtf

### ISSUE THREAD

**Issue by Squuv** [trustedsec/social-engineer-toolkit#778]
pip3 install -r requirements.txt
```

....Requirement already satisfied: pillow in /usr/lib/python3/dist-packages (from -r requirements.txt (line 9)) (7.0.0)
Collecting pymssql<3.0
  Using cached pymssql-2.1.4.tar.gz (691 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lxir2h08/pymssql/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lxir2h08/pymssql/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-lxir2h08/pymssql/pip-egg-info                                                                                    
         cwd: /tmp/pip-install-lxir2h08/pymssql/                                                      
    Complete output (9 lines):                                                                        
    /usr/lib/python3/dist-packages/setuptools/dist.py:46: DistDeprecationWarning: Do not call this function                                                                                                 
      warnings.warn("Do not call this function", DistDeprecationWarning)                              
    Traceback (most recent call last):                                                                
      File "<string>", line 1, in <module>                                                            
      File "/tmp/pip-install-lxir2h08/pymssql/setup.py", line 160, in <module>                        
        print("setup.py: platform.linux_distribution() => %r" % (platform.linux_distribution(),))     
    AttributeError: module 'platform' has no attribute 'linux_distribution'                           
    setup.py: platform.system() => 'Linux'                                                            
    setup.py: platform.architecture() => ('64bit', 'ELF')                                             
    ----------------------------------------                                                          
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by HackingDave** [comment]
Addressed in SET 8.1.1 as part of the packaging, dependency, and Python runtime modernization. Please pull latest master and open a new issue with current reproduction steps if the problem still occurs.
