### ISSUE TITLE
cannot install in my Mac set toolkit doesn't work

### ISSUE THREAD

**Issue by naveenbhoga** [trustedsec/social-engineer-toolkit#779]
ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/tv/rll347qs2w90bq2cqdz_8v440000gn/T/pip-install-7ejccz90/pymssql/setup.py'"'"'; __file__='"'"'/private/var/folders/tv/rll347qs2w90bq2cqdz_8v440000gn/T/pip-install-7ejccz90/pymssql/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/tv/rll347qs2w90bq2cqdz_8v440000gn/T/pip-pip-egg-info-yf_25s9g
         cwd: /private/var/folders/tv/rll347qs2w90bq2cqdz_8v440000gn/T/pip-install-7ejccz90/pymssql/
    Complete output (7 lines):
    /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/dist.py:45: DistDeprecationWarning: Do not call this function
      warnings.warn("Do not call this function", DistDeprecationWarning)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/tv/rll347qs2w90bq2cqdz_8v440000gn/T/pip-install-7ejccz90/pymssql/setup.py", line 88, in <module>
        from Cython.Distutils import build_ext as _build_ext
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by andyboltondev** [comment]
I'm getting the same error on Windows 10.
Could this be related to pymssql being discontinued (as per the comment in the requirements.txt)

**Comment by juangm** [comment]
I am using MacOS and I have similar problem.
I solved installing the `Cython` package before doing the installation: `pip3 install --upgrade cython`

**Comment by HackingDave** [comment]
Addressed in SET 8.1.1 as part of the packaging, dependency, and Python runtime modernization. Please pull latest master and open a new issue with current reproduction steps if the problem still occurs.
