### ISSUE TITLE
Error encountered during installation command: pip3 install -r requirements.txt 

### ISSUE THREAD

**Issue by tgibson1** [trustedsec/social-engineer-toolkit#788]
Error encountered during installation command: pip3 install -r requirements.txt 

tim@tim-MS-7977:~/socialEngineering/setoolkit$ pip3 install -r requirements.txt 
Requirement already satisfied: pexpect in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (4.6.0)
Requirement already satisfied: pycrypto in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (2.6.1)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (2.22.0)
Requirement already satisfied: pyopenssl in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4)) (19.0.0)
Collecting pefile
  Using cached pefile-2019.4.18.tar.gz (62 kB)
Collecting impacket
  Using cached impacket-0.9.21.tar.gz (1.3 MB)
Collecting qrcode
  Using cached qrcode-6.1-py2.py3-none-any.whl (31 kB)
Requirement already satisfied: pillow in /usr/lib/python3/dist-packages (from -r requirements.txt (line 9)) (7.0.0)
Collecting pymssql<3.0
  Using cached pymssql-2.1.4.tar.gz (691 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-shk44ywk/pymssql/setup.py'"'"'; __file__='"'"'/tmp/pip-install-shk44ywk/pymssql/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-shk44ywk/pymssql/pip-egg-info
         cwd: /tmp/pip-install-shk44ywk/pymssql/
    Complete output (7 lines):
    /usr/lib/python3/dist-packages/setuptools/dist.py:46: DistDeprecationWarning: Do not call this function
      warnings.warn("Do not call this function", DistDeprecationWarning)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-shk44ywk/pymssql/setup.py", line 88, in <module>
        from Cython.Distutils import build_ext as _build_ext
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
tim@tim-MS-7977:~/socialEngineering/setoolkit$

**Comment by lookcrabs** [comment]
What version of python are you using? Try adding Cython to requirements or just install cython with `pip3 install cython` 

On top of that pymsql has been discontinued. So overall this project is kind of dead until someone updates it to use an alternative. Maybe https://turbodbc.readthedocs.io/en/latest/ or https://github.com/zillow/ctds? 

I think your best bet to get up and running asap currently is just spawning a docker or something with an older version of python (3.5?) and using that:

```
docker run -it -p 80:80 -p 443:443 -p 5000:5000 -v ${FULL_PATH_TO_THIS_REPO}:/mnt/ --entrypoint='' python:3.5 /bin/bash
$ cd /mnt/
$ python setup.py
$ setoolkit 
```

Good luck

**Comment by HackingDave** [comment]
Addressed in SET 8.1.1 as part of the packaging, dependency, and Python runtime modernization. Please pull latest master and open a new issue with current reproduction steps if the problem still occurs.
