### ISSUE TITLE
setoolkit "Exception happened"

### ISSUE THREAD

**Issue by Xam-Mlr** [trustedsec/social-engineer-toolkit#827]
Bonjour je débute dans le monde du hacking et j'ai essayé setoolkit version 8.0.3
j'ai entré option 1 ensuite 2 après 3 en après 2 bref j'ai cloner un site jusqu'à là tous se passait bien j'ai rentré mon ip sur mon navigateur et j'ai trouvé la page que j'avais cloner j'ai remplis le formulaire et valider, mais j'ai reçu un message d'erreur,

Exception happened during processing of request from ('mon adresse ip', 49294)                                                                               
Traceback (most recent call last):                                                                                                                         
  File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread                                                                           
    self.finish_request(request, client_address)                                                                                                           
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request                                                                                   
    self.RequestHandlerClass(request, client_address, self)                                                                                                
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__                                                                                         
    self.handle()                                                                                                                                          
  File "/usr/lib/python3.8/http/server.py", line 427, in handle                                                                                            
    self.handle_one_request()                                                                                                                              
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request                                                                                
    method()                                                                                                                                               
  File "/usr/share/set/src/webattack/harvester/harvester.py", line 334, in do_POST                                                                         
    filewrite.write(cgi.escape("PARAM: " + line + "\n"))                                                                                                   
AttributeError: module 'cgi' has no attribute 'escape' 

je ne comprend rien !

j'espere que vous pourrez m'aider

**Comment by HackingDave** [comment]
Addressed in SET 8.1.1 as part of the Python 3 web attack, credential harvester, static file, SSL, and legacy payload handling fixes. Please pull latest master and open a new issue with current reproduction steps if the problem still occurs.
