### ISSUE TITLE
Harvester problem

### ISSUE THREAD

**Issue by ghero** [trustedsec/social-engineer-toolkit#850]
I'm running this on Debian:
Linux 5.10.11-v7l+ #1399 SMP Thu Jan 28 12:09:48 GMT 2021 armv7l GNU/Linux
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

[*] The Social-Engineer Toolkit Credential Harvester Attack
[*] Credential Harvester is running on port 443
[*] Information will be displayed to you as it arrives below:
[*] Starting built-in SSL server

----------------------------------------
Exception happened during processing of request from ('192.168.1.150', 64468)
Traceback (most recent call last):
  File "./setoolkit", line 244, in <module>
    core.module_reload(src.core.set)
NameError: name 'src' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/setoolkit/src/core/set.py", line 606, in <module>
    module_reload(harvester)
NameError: name 'harvester' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 394, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.7/dist-packages/OpenSSL/SSL.py", line 1734, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.7/dist-packages/OpenSSL/SSL.py", line 1566, in _raise_ssl_error
    _raise_current_error()
  File "/usr/local/lib/python3.7/dist-packages/OpenSSL/_util.py", line 57, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')]
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.168.1.150', 64469)
Traceback (most recent call last):
  File "./setoolkit", line 244, in <module>
    core.module_reload(src.core.set)
NameError: name 'src' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/setoolkit/src/core/set.py", line 606, in <module>
    module_reload(harvester)
NameError: name 'harvester' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 394, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.7/dist-packages/OpenSSL/SSL.py", line 1734, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.7/dist-packages/OpenSSL/SSL.py", line 1566, in _raise_ssl_error
    _raise_current_error()
  File "/usr/local/lib/python3.7/dist-packages/OpenSSL/_util.py", line 57, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')]
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.168.1.150', 64486)
Traceback (most recent call last):
  File "./setoolkit", line 244, in <module>
    core.module_reload(src.core.set)
NameError: name 'src' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/setoolkit/src/core/set.py", line 606, in <module>
    module_reload(harvester)
NameError: name 'harvester' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 394, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.7/dist-packages/OpenSSL/SSL.py", line 1734, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.7/dist-packages/OpenSSL/SSL.py", line 1566, in _raise_ssl_error
    _raise_current_error()
  File "/usr/local/lib/python3.7/dist-packages/OpenSSL/_util.py", line 57, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'tlsv1 alert unknown ca')]
----------------------------------------
192.168.1.150 - - [22/Feb/2021 15:37:05] "GET / HTTP/1.1" 200 -
192.168.1.150 - - [22/Feb/2021 15:37:09] "GET / HTTP/1.1" 200 -

**Comment by HackingDave** [comment]
Addressed in SET 8.1.1 as part of the Python 3 web attack, credential harvester, static file, SSL, and legacy payload handling fixes. Please pull latest master and open a new issue with current reproduction steps if the problem still occurs.
