### ISSUE TITLE
WSL not launching SETOOLKIT

### ISSUE THREAD

**Issue by queenbtrice** [trustedsec/social-engineer-toolkit#918]
Greetings everyone! 

Not really sure how this works but I've been trying to launch setoolkit for awhile now and I thought that I had everything sorted out because I uninstalled it for the 2nd time because it stopped working and I expected it to work because I got this message : 

[*] Installing setoolkit to /usr/share/setoolkit..
/home/queenbtrice/setoolkit
[*] Creating launcher for setoolkit...
[*] Done. Chmoding +x....
[*] Finished. Run 'setoolkit' to start the Social Engineer Toolkit.

So I thought oh yay I did it but when I ran 'setoolkit' it showed the same message that led me into uninstalling it : 

┌──(root)-[/home/queenbtrice/setoolkit]
└─# setoolkit
Traceback (most recent call last):
  File "/usr/share/setoolkit/./setoolkit", line 17, in <module>
    import src.core.setcore as core
  File "/usr/share/setoolkit/src/core/setcore.py", line 48, in <module>
    from Crypto.Cipher import AES
  File "/usr/local/lib/python3.9/dist-packages/Crypto/Cipher/AES.py", line 52, in <module>
    class AESCipher (blockalgo.BlockAlgo):
AttributeError: module 'Crypto.Cipher.blockalgo' has no attribute 'BlockAlgo'

Please help!!  Thank you.

**Comment by dvenomuzj96** [comment]
I've managed to install kali and SET on two devices. Oddly enough my first install suddenly stopped working and my second install is fine. I can't seem to get the first one working after several attempts. I'm actually stuck at the same section as you, but my error is slightly different:

 Traceback (most recent call last):
  File "/home/dvnmuzj/setoolkit/./setoolkit", line 17, in <module>
    import src.core.setcore as core
ValueError: source code string cannot contain null bytes

My other install hasn't had any issues yet. They are both on ARM64, but the first is on an older machine that usually uses x86 programs. It worked for a week, then I stopped using the machine for two or three days due to using the second machine. When I came back to the original install, it would only give me this error. I've uninstalled and reinstalled kali twice and still the same error.

**Comment by HackingDave** [comment]
Addressed in SET 8.1.1 as part of the packaging, dependency, and Python runtime modernization. Please pull latest master and open a new issue with current reproduction steps if the problem still occurs.
